export { default as TabPage } from './TabPage'
export { default as CanvasPage } from './CanvasPage'
export { default as AntdThemePage } from './AntdThemePage'
export { default as ThreeJSPage } from './ThreeJSPage'
export { default as WebGLPage } from './WebGLPage'
export { default as SlatePage } from './SlatePage'
